service: treatout-api
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  hello:
    handler: handler.hello
  createPlace:
    handler: places.create
    events:
      - http:
          path: places/create
          method: post
          cors: true
  listPlace:
    handler: places.list
    events:
      - http:
          path: places
          method: get
          cors: true
  getPlace:
    handler: places.get
    events:
      - http:
          path: places/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  deleltePlace:
    handler: places.delete
    events:
      - http:
          path: places/delete/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: false
resources:
    - ${file(resources/tables.yml)}
    
plugins:
    - serverless-dynamodb-local
    - serverless-offline

custom:
  dynamodb:
    start:
      migrate: true